function Hd = MATLAB_designed_filter
    %MATLAB_DESIGNED_FILTER Returns a discrete-time filter object.
    
    % MATLAB Code
    % Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
    % Generated on: 1-Mar-2024 14:07:57
    
    % Equiripple Lowpass filter designed using the FIRPM function.
    
    % All frequency values are normalized to 1.
    
    Fpass = 0.2;             % Passband Frequency
    Fstop = 0.23;            % Stopband Frequency
    Dpass = 0.057501127785;  % Passband Ripple
    Dstop = 0.0001;          % Stopband Attenuation
    dens  = 20;              % Density Factor
    
    % Calculate the order from the parameters using FIRPMORD.
    [N, Fo, Ao, W] = firpmord([Fpass, Fstop], [1 0], [Dpass, Dstop]);
    
    % Calculate the coefficients using the FIRPM function.
    b  = firpm(N, Fo, Ao, W, {dens});
    Hd = dfilt.dffir(b);
    
    % ----- new code -----

    freqz(b,1);

    % quantize the coefficients
    new_coeffs = quantizenumeric(b, 1, 16, 13, "nearest");
    % freqz(new_coeffs, 1); % show the frequency response

    % print coefficients to a file
    print_filter_coefficients(new_coeffs, "./../main_HDL/filter_coefficients.sv");
    
end
